name: flashapp
description: A flutter app which basically for chatting using firebase

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.1.1
  cloud_firestore: ^1.0.3
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  modal_progress_hud: ^0.1.3
  intl_phone_field: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  assets:
    - images/

